package core

// map used to get the language of the parsed files based on the suffix.
var extToLanguage = map[string]string{
	".go":    "Go",
	".c":     "C",
	".h":     "C Headers",
	".cpp":   "C++",
	".hpp":   "C++ Headers",
	".js":    "JavaScript",
	".ts":    "TypeScript",
	".java":  "Java",
	".py":    "Python",
	".sh":    "Shell",
	".sql":   "SQL",
	".html":  "HTML",
	".htm":   "HTML",
	".rb":    "Ruby",
	".lua":   "Lua",
	".rs":    "Rust",
	".txt":   "Text",
	".md":    "Markdown",
	".bash":  "Bash",
	".php":   "PHP",
	".json":  "JSON",
	".yaml":  "YAML",
	".yml":   "YAML",
	".hs":    "Haskell",
	".kts":   "Kotlin",
	".kt":    "Kotlin",
	".swift": "Swift",
	".exs":   "Elixir",
	".ex":    "Elixir",
	".cljs":  "Clojure",
	".clj":   "Clojure",
	".r":     "R",
	".dart":  "Dart",
	".css":   "CSS",
	".scss":  "SCSS",
	".ini":   "Ini",
	".toml":  "TOML",
	".xml":   "XML",
	".ps1":   "PowerShell",
	".tf":    "Terraform",
	".m":     "Objective-C",
	".rst":   "reStructuredText",
	".asm":   "Assembly",
	".s":     "Assembly",
	".S":     "Assembly",
	".mk":    "Makefile",
	".pl":    "Perl",
	".pm":    "Perl",
	".t":     "Perl",
	".pod":   "Perl",
	".plx":   "Perl",
	".perl":  "Perl",
	".al":    "Perl",
	".psgi":  "Perl",
	".cgi":   "Perl",
}

// Defining the comment semantics of the languages.
var commentSyntax = map[string]commentMarkers{
	"Go":          {Line: "//", Open: "/*", Close: "*/"},
	"C":           {Line: "//", Open: "/*", Close: "*/"},
	"C++":         {Line: "//", Open: "/*", Close: "*/"},
	"JavaScript":  {Line: "//", Open: "/*", Close: "*/"},
	"TypeScript":  {Line: "//", Open: "/*", Close: "*/"},
	"Java":        {Line: "//", Open: "/*", Close: "*/"},
	"PHP":         {Line: "//", Open: "/*", Close: "*/"},
	"Kotlin":      {Line: "//", Open: "/*", Close: "*/"},
	"Switft":      {Line: "//", Open: "/*", Close: "*/"},
	"Dart":        {Line: "//", Open: "/*", Close: "*/"},
	"XML":         {Line: "//", Open: "/*", Close: "*/"},
	"Terraform":   {Line: "//", Open: "/*", Close: "*/"},
	"SCSS":        {Line: "//", Open: "/*", Close: "*/"},
	"Rust":        {Line: "//"},
	"CSS":         {Open: "/*", Close: "*/"},
	"Perl":        {Line: "#", Open: "=pod", Close: "=cut"},
	"PowerShell":  {Line: "#", Open: "<#", Close: "#>"},
	"Assembly":    {Line: "#", Open: "/*", Close: "*/"},
	"Make":        {Line: "#"},
	"Python":      {Line: "#"},
	"TOML":        {Line: "#"},
	"Shell":       {Line: "#"},
	"Bash":        {Line: "#"},
	"Ruby":        {Line: "#"},
	"YAML":        {Line: "#"},
	"Elixir":      {Line: "#"},
	"R":           {Line: "#"},
	"SQL":         {Line: "--", Open: "/*", Close: "*/"},
	"Lua":         {Line: "--", Open: "--[[", Close: "]]"},
	"Haskell":     {Line: "--", Open: "{-", Close: "-}"},
	"HTML":        {Open: "<!--", Close: "-->"},
	"Clojure":     {Line: ";"},
	"Ini":         {Line: ";"},
	"Objective-C": {Line: "%", Open: "%{", Close: "}%"},
}
