/*
SPDX-License-Identifier: GPL-3.0-only
Copyright (c) 2026 Alvesafk.

langs.go has maps and slices that are used to identify the language and/or file.
*/
package core

// map used to get the language of the parsed files based on the suffix.
var extToLanguage = map[string]string{
	".go":    "Go",
	".c":     "C",
	".h":     "C Headers",
	".cpp":   "C++",
	".hpp":   "C++ Headers",
	".cs":    "C#",
	".js":    "JavaScript",
	".jsx":   "JavaScript React",
	".ts":    "TypeScript",
	".tsx":   "TypeScript React",
	".java":  "Java",
	".py":    "Python",
	".sh":    "Shell",
	".sql":   "SQL",
	".html":  "HTML",
	".htm":   "HTML",
	".rb":    "Ruby",
	".lua":   "Lua",
	".rs":    "Rust",
	".txt":   "Text",
	".md":    "Markdown",
	".bash":  "Bash",
	".zsh":   "Zsh",
	".fish":  "Fish",
	".php":   "PHP",
	".json":  "JSON",
	".jsonc": "JSONC",
	".yaml":  "YAML",
	".yml":   "YAML",
	".hs":    "Haskell",
	".kts":   "Kotlin",
	".kt":    "Kotlin",
	".swift": "Swift",
	".exs":   "Elixir",
	".ex":    "Elixir",
	".cljs":  "Clojure",
	".clj":   "Clojure",
	".r":     "R",
	".dart":  "Dart",
	".css":   "CSS",
	".scss":  "SCSS",
	".ini":   "Ini",
	".toml":  "TOML",
	".xml":   "XML",
	".ps1":   "PowerShell",
	".tf":    "Terraform",
	// NOTE: ".m" is ambiguous between Objective-C and MATLAB by extension
	// alone. We keep it mapped to Objective-C for now; disambiguating
	// correctly requires peeking at file content (e.g. "#import"/"@interface"
	// vs "function"/"%" comments) rather than just the suffix.
	".m":          "Objective-C",
	".rst":        "reStructuredText",
	".asm":        "Assembly",
	".s":          "Assembly",
	".S":          "Assembly",
	".mk":         "Makefile",
	".pl":         "Perl",
	".pm":         "Perl",
	".t":          "Perl",
	".pod":        "Perl",
	".plx":        "Perl",
	".perl":       "Perl",
	".al":         "Perl",
	".psgi":       "Perl",
	".cgi":        "Perl",
	".scala":      "Scala",
	".sc":         "Scala",
	".groovy":     "Groovy",
	".gvy":        "Groovy",
	".gy":         "Groovy",
	".gsh":        "Groovy",
	".zig":        "Zig",
	".fs":         "F#",
	".fsi":        "F#",
	".fsx":        "F#",
	".vb":         "Visual Basic",
	".bas":        "Visual Basic",
	".erl":        "Erlang",
	".hrl":        "Erlang",
	".dockerfile": "Dockerfile",
	".bat":        "Bat",
	".svg":        "SVG",
	".y":          "yacc",
	".po":         "PO File",
	".l":          "lex",
	".awk":        "awk",
	".csv":        "CSV",
	".jinja":      "Jinja Template",
	".jinja2":     "Jinja Template",
	".build":      "NAnt script",
	".ui":         "XML (Qt/GTK)",
	".xm":         "Logos",
	".x":          "Logos",
	".xsd":        "XSD",
	".feature":    "Cucumber",
	".tex":        "TeX",
	".ttcn":       "TNSDL",
	".ttcn3":      "TNSDL",
	".def":        "Windows Module Definition",
	".ld":         "Linker Script",
	".smk":        "Snakemake",
	".m4":         "m4",
	".xsl":        "XSLT",
	".xslt":       "XSLT",
	".bb":         "BitBake",
	".bbappend":   "BitBake",
	".um":         "Umka",
	".sed":        "sed",
	".vim":        "vim script",
	".vm":         "Velocity Template Language",
}

// Defining the comment semantics of the languages.
var commentSyntax = map[string]commentMarkers{
	"Go":                         {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"C":                          {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"C Headers":                  {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"C++":                        {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"C++ Headers":                {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"C#":                         {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"JavaScript":                 {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"JavaScript React":           {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"TypeScript":                 {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"TypeScript React":           {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"Java":                       {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"JSONC":                      {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"PHP":                        {Line: []string{"//", "#"}, Open: "/*", Close: "*/"},
	"Kotlin":                     {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"Swift":                      {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"Dart":                       {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"Terraform":                  {Line: []string{"//", "#"}, Open: "/*", Close: "*/"},
	"SCSS":                       {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"Rust":                       {Line: []string{"//"}},
	"CSS":                        {Open: "/*", Close: "*/"},
	"Perl":                       {Line: []string{"#"}, Open: "=pod", Close: "=cut"},
	"PowerShell":                 {Line: []string{"#"}, Open: "<#", Close: "#>"},
	"Assembly":                   {Line: []string{";", "//", "#"}, Open: "/*", Close: "*/"},
	"Makefile":                   {Line: []string{"#"}},
	"Python":                     {Line: []string{"#"}},
	"TOML":                       {Line: []string{"#"}},
	"Shell":                      {Line: []string{"#"}},
	"Bash":                       {Line: []string{"#"}},
	"Zsh":                        {Line: []string{"#"}},
	"Fish":                       {Line: []string{"#"}},
	"Ruby":                       {Line: []string{"#"}},
	"YAML":                       {Line: []string{"#"}},
	"Elixir":                     {Line: []string{"#"}},
	"R":                          {Line: []string{"#"}},
	"SQL":                        {Line: []string{"--"}, Open: "/*", Close: "*/"},
	"Lua":                        {Line: []string{"--"}, Open: "--[[", Close: "]]"},
	"Haskell":                    {Line: []string{"--"}, Open: "{-", Close: "-}"},
	"HTML":                       {Open: "<!--", Close: "-->"},
	"XML":                        {Open: "<!--", Close: "-->"},
	"Clojure":                    {Line: []string{";"}},
	"Ini":                        {Line: []string{";", "#"}},
	"Objective-C":                {Line: []string{"%"}, Open: "%{", Close: "}%"},
	"Scala":                      {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"Groovy":                     {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"Zig":                        {Line: []string{"//"}},
	"F#":                         {Line: []string{"//"}, Open: "(*", Close: "*)"},
	"Erlang":                     {Line: []string{"%"}},
	"Visual Basic":               {Line: []string{"'"}},
	"Dockerfile":                 {Line: []string{"#"}},
	"Nginx":                      {Line: []string{"#"}},
	"Apache":                     {Line: []string{"#"}},
	"reStructuredText":           {Line: []string{".."}},
	"SVG":                        {Open: "<!--", Close: "-->"},
	"yacc":                       {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"PO File":                    {Line: []string{"#"}},
	"lex":                        {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"awk":                        {Line: []string{"#"}},
	"Jinja Template":             {Open: "{#", Close: "#}"},
	"NAnt script":                {Open: "<!--", Close: "-->"},
	"XML (Qt/GTK)":               {Open: "<!--", Close: "-->"},
	"Logos":                      {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"XSD":                        {Open: "<!--", Close: "-->"},
	"Cucumber":                   {Line: []string{"#"}},
	"TeX":                        {Line: []string{"%"}},
	"TNSDL":                      {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"Windows Module Definition":  {Line: []string{";"}},
	"Linker Script":              {Line: []string{"//"}, Open: "/*", Close: "*/"},
	"Snakemake":                  {Line: []string{"#"}},
	"m4":                         {Line: []string{"dnl"}},
	"XSLT":                       {Open: "<!--", Close: "-->"},
	"BitBake":                    {Line: []string{"#"}},
	"Umka":                       {Line: []string{"//"}},
	"sed":                        {Line: []string{"#"}},
	"vim script":                 {Line: []string{"\""}},
	"Velocity Template Language": {Line: []string{"##"}, Open: "#*", Close: "*#"},
}

var extToIgnore = []string{
	".mod",
	".sum",
}

var filenameException = map[string]string{
	"Makefile":   "Makefile",
	"makefile":   "Makefile",
	"Dockerfile": "Dockerfile",
	"dockerfile": "Dockerfile",
	"Snakefile":  "Snakemake",
	"snakefile":  "Snakemake",
}

var filenameToIgnore = []string{
	"LICENSE",
	"node_modules",
}
